name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn

      - name: Build site
        run: |
          yarn install
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
